services:
  blogzio-server:
    build:
      context: .
      dockerfile: server/dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      VISITOR_SECRET: ${VISITOR_SECRET}
  blogzio-client:
    build:
      context: .
      dockerfile: client/dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
