spring.config.import=optional:file:../.env[.properties]

spring.application.name=blogzio

server.port=8081

spring.datasource.url=jdbc:h2:mem:openapi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secretKey=${AWS_SECRET_KEY}
spring.cloud.aws.s3.endpoint=${AWS_S3_ENDPOINT}
spring.cloud.aws.s3.path-style-access-enabled=true
spring.cloud.aws.s3.region=${AWS_REGION}
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.h2.console.enabled=false

jwt.secret=${JWT_SECRET}

springdoc.api-docs.enabled=true
