server.port=8081

spring.datasource.url=jdbc:h2:mem:openapi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.cloud.aws.credentials.accessKey=THfjViog4owArWluIq5n
spring.cloud.aws.credentials.secretKey=oxhFpJRrcIR1snmdwYb87arRMHz7paltm4g6S2WM
spring.cloud.aws.s3.endpoint=http://localhost:9000
spring.cloud.aws.s3.path-style-access-enabled=true
spring.cloud.aws.s3.region=us-east-1
spring.cloud.aws.s3.bucket=blogzio

# ?? ?? ??
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.h2.console.enabled=true

jwt.secret=openapi-profile-dummy-secret-key-32chars

springdoc.api-docs.enabled=true
