/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGuestbookMessageRequest,
  CreateGuestbookMessageResponse,
} from '../models/index';
import {
    CreateGuestbookMessageRequestFromJSON,
    CreateGuestbookMessageRequestToJSON,
    CreateGuestbookMessageResponseFromJSON,
    CreateGuestbookMessageResponseToJSON,
} from '../models/index';

export interface CreateRequest {
    createGuestbookMessageRequest: CreateGuestbookMessageRequest;
}

/**
 * 
 */
export class GuestbookControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for create without sending the request
     */
    async createRequestOpts(requestParameters: CreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createGuestbookMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'createGuestbookMessageRequest',
                'Required parameter "createGuestbookMessageRequest" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/guestbook/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGuestbookMessageRequestToJSON(requestParameters['createGuestbookMessageRequest']),
        };
    }

    /**
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateGuestbookMessageResponse>> {
        const requestOptions = await this.createRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateGuestbookMessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateGuestbookMessageResponse> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
