/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuestbookMessageResponse
 */
export interface CreateGuestbookMessageResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateGuestbookMessageResponse
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateGuestbookMessageResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CreateGuestbookMessageResponse interface.
 */
export function instanceOfCreateGuestbookMessageResponse(value: object): value is CreateGuestbookMessageResponse {
    return true;
}

export function CreateGuestbookMessageResponseFromJSON(json: any): CreateGuestbookMessageResponse {
    return CreateGuestbookMessageResponseFromJSONTyped(json, false);
}

export function CreateGuestbookMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuestbookMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function CreateGuestbookMessageResponseToJSON(json: any): CreateGuestbookMessageResponse {
    return CreateGuestbookMessageResponseToJSONTyped(json, false);
}

export function CreateGuestbookMessageResponseToJSONTyped(value?: CreateGuestbookMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

