/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuestbookMessageRequest
 */
export interface CreateGuestbookMessageRequest {
    /**
     * 
     * @type {CreateGuestbookMessageRequestContentTypeEnum}
     * @memberof CreateGuestbookMessageRequest
     */
    contentType?: CreateGuestbookMessageRequestContentTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof CreateGuestbookMessageRequest
     */
    content?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestbookMessageRequest
     */
    password?: string;
}


/**
 * @export
 */
export const CreateGuestbookMessageRequestContentTypeEnum = {
    Text: 'TEXT',
    Image: 'IMAGE'
} as const;
export type CreateGuestbookMessageRequestContentTypeEnum = typeof CreateGuestbookMessageRequestContentTypeEnum[keyof typeof CreateGuestbookMessageRequestContentTypeEnum];


/**
 * Check if a given object implements the CreateGuestbookMessageRequest interface.
 */
export function instanceOfCreateGuestbookMessageRequest(value: object): value is CreateGuestbookMessageRequest {
    return true;
}

export function CreateGuestbookMessageRequestFromJSON(json: any): CreateGuestbookMessageRequest {
    return CreateGuestbookMessageRequestFromJSONTyped(json, false);
}

export function CreateGuestbookMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuestbookMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'content': json['content'] == null ? undefined : json['content'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function CreateGuestbookMessageRequestToJSON(json: any): CreateGuestbookMessageRequest {
    return CreateGuestbookMessageRequestToJSONTyped(json, false);
}

export function CreateGuestbookMessageRequestToJSONTyped(value?: CreateGuestbookMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentType': value['contentType'],
        'content': value['content'],
        'password': value['password'],
    };
}

