/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/post/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getList"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guestbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/admin-exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 관리자 계정 존재 여부를 확인합니다. */
        get: operations["getAdminExists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guestbook/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonNode: unknown;
        PostUpdateRequest: {
            title?: string;
            content?: components["schemas"]["JsonNode"];
            pinned?: boolean;
            isVisible?: boolean;
            /** Format: uuid */
            categoryId?: string;
            tags?: string[];
        };
        Category: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** Format: int32 */
            sortOrder?: number;
            /** @enum {string} */
            type?: "GALLERY" | "LIST";
            posts?: components["schemas"]["Post"][];
        };
        Post: {
            /** Format: uuid */
            id?: string;
            author?: components["schemas"]["User"];
            title?: string;
            content?: components["schemas"]["JsonNode"];
            pinned?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            postedAt?: string;
            /** Format: int32 */
            likes?: number;
            is_visiable?: boolean;
            category?: components["schemas"]["Category"];
            tags?: components["schemas"]["Tag"][];
        };
        PostResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            content?: components["schemas"]["JsonNode"];
            /** Format: int32 */
            likes?: number;
            is_visiable?: boolean;
            /** Format: date-time */
            postedAt?: string;
            tags?: components["schemas"]["Tag"][];
        };
        Tag: {
            /** Format: uuid */
            id?: string;
            title?: string;
            posts?: components["schemas"]["Post"][];
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            email?: string;
            password?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CategoryUpdateRequest: {
            name: string;
            slug: string;
        };
        CategoryResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** Format: int32 */
            sortOrder?: number;
            /** @enum {string} */
            type?: "GALLERY" | "LIST";
        };
        UserRequest: {
            username?: string;
            email?: string;
            password?: string;
        };
        UserResponse: {
            message?: string;
        };
        PostCreateRequest: {
            title?: string;
            content?: components["schemas"]["JsonNode"];
            pinned?: boolean;
            isVisible?: boolean;
            /** Format: uuid */
            categoryId?: string;
            tags?: string[];
        };
        CreateGuestbookMessageRequest: {
            nickname: string;
            /** @enum {string} */
            contentType: "TEXT" | "IMAGE";
            content: string;
            password: string;
            /** @enum {string} */
            backgroundColor?: "WHITE" | "PINK" | "YELLOW" | "LIME" | "SKY" | "VIOLET";
        };
        CreateGuestbookMessageResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CategoryCreateRequset: {
            name: string;
            slug: string;
            /** @enum {string} */
            type?: "GALLERY" | "LIST";
        };
        LoginRequest: {
            username?: string;
            password?: string;
        };
        LoginResponse: {
            accessToken?: string;
        };
        CreateAssetRequest: {
            /** Format: binary */
            file: string;
        };
        CreateAssetResponse: {
            url: string;
        };
        UserAdminExistsResponse: {
            exists: boolean;
        };
        PostGetListResponse: {
            posts: components["schemas"]["PostResponse"][];
            /** Format: int32 */
            totalPages: number;
        };
        GetAllGuestbookMessagesResponse: {
            messages?: components["schemas"]["GuestbookMessageDto"][];
        };
        GuestbookMessageDto: {
            /** Format: uuid */
            id: string;
            nickname: string;
            /** @enum {string} */
            contentType: "TEXT" | "IMAGE";
            content: string;
            /** @enum {string} */
            backgroundColor?: "WHITE" | "PINK" | "YELLOW" | "LIME" | "SKY" | "VIOLET";
            /** Format: date-time */
            createdAt: string;
        };
        DeleteGuestbookMessageRequest: {
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    getList: {
        parameters: {
            query?: {
                category?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostGetListResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetAllGuestbookMessagesResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuestbookMessageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateGuestbookMessageResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequset"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateAssetResponse"];
                };
            };
        };
    };
    getAdminExists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserAdminExistsResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteGuestbookMessageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
